theme = "tokyonight"

[editor]
line-number = "relative"
mouse = false

[keys.insert]
j = { k = "normal_mode" }

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
